jobs:
- job: copr_build
  metadata:
    targets:
    - fedora-all-x86_64
    - epel-8-x86_64
    - epel-9-x86_64
  trigger: pull_request
- job: tests
  metadata:
    targets:
    - fedora-all-x86_64
  trigger: pull_request
actions:
  get-current-version:
  - bash -c "source release_tools/versions.sh && echo ${version}"
downstream_package_name: openscap
upstream_package_name: openscap
specfile_path: openscap.spec
