sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y autoconf automake libtool lcov libdbus-1-dev libdbus-glib-1-dev libcurl4-openssl-dev libgcrypt-dev libselinux1-dev libgconf2-dev libacl1-dev libblkid-dev libcap-dev libxml2-dev swig libxml-parser-perl libxml-xpath-perl libperl-dev librpm-dev swig librtmp-dev

language: c

before_script:
  - export CC=gcc-7 GCOV=gcov-7
  - ./autogen.sh
  - mkdir build
  - cd build

script:
  - ../configure CFLAGS="-O0" && build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - ../configure CFLAGS="--coverage -ftest-coverage -fprofile-arcs" LDFLAGS=-lgcov --enable-debug && make
  - make -k check VERBOSE=true
  - $GCOV -i src/.libs/*.gcno utils/*.gcno
  - cd .. && sonar-scanner

addons:
  sonarcloud:
    organization: "matejak-github"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7


cache:
  directories:
    - '$HOME/.sonar/cache'
